
cards_list:
    path: /expansion/{expansion_code}/{view}/{sort}/{page}
    defaults:
        _controller: AppBundle:Search:list
        view: list
        sort: set
        page: 1

cards_faction:
    path: /faction/{faction_code}/{view}/{sort}/{page}
    defaults:
        _controller: AppBundle:Search:listFactions
        view: list
        sort: faction
        page: 1

cards_zoom:
    path: /card/{card_code}
    defaults:
        _controller: AppBundle:Search:zoom

cards_search:
    path: /search
    defaults:
        _controller: AppBundle:Search:form

cards_find:
    path: /find
    defaults:
        _controller: AppBundle:Search:find

cards_processSearchForm:
    path: /process
    defaults:
        _controller: AppBundle:Search:process
