AppBundle\Entity\Expansion:
    type: entity
    table: expansion
    repositoryClass: AppBundle\Repository\ExpansionRepository
    oneToMany:
        cards:
            targetEntity: Card
            orderBy: {'position':'ASC'}
            mappedBy: expansion
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 1024
            nullable: false
        position:
            type: smallint
            nullable: false
        size:
            type: smallint
            nullable: false
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
    uniqueConstraints:
        expansion_code_idx:
            columns: [ code ]
