AppBundle\Entity\Faction:
    type: entity
    table: faction
    repositoryClass: AppBundle\Repository\FactionRepository
    oneToMany:
        cards:
            targetEntity: Card
            orderBy: {'code':'ASC'}
            mappedBy: faction
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 1024
            nullable: false
        octgnId:
            type: string
            nullable: true
            column: octgn_id
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
    uniqueConstraints:
        faction_code_idx:
            columns: [ code ]
